DRIVER_CAMERA_ID:
  "192.168.1.200"
FRONT_CAMERA_ID:
  "192.168.1.201"
REAR_CAMERA_ID:
  "192.168.1.100"

LEFT_CAMERA_ID:
  "192.168.1.200"
RIGHT_CAMERA_ID:
  "192.168.1.100"

RED_ALERT_SIGNAL: 2
YELLOW_ALERT_SIGNAL: 1
NO_ALERT_SIGNAL: 99

YELLOW_ALERT_DISTANCE: 6000 # in mm
RED_ALERT_DISTANCE: 1000 # in mm

HEAD_DOSE_COUNT: 5
HEAD_TILT_COUNT: 5
YAWN_COUNT: 5
FATIGUE_TOTAL_COUNT: 8

# 234:416
MainImage_Height: 234
MainImage_Width: 416
DriverImage_Height: 420
DriverImage_Width: 540

MainWindowDimention: [1028, 846]

Record_Seconds: 10
Record_Total : 6

PRODUCTION: true